---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system
  - gem install bundler -v 2.0.1

script:
  - bundle exec rspec
